version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.20.0-alpine
    volumes:
      - ./tempHomepage:/etc/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flashcards-api
      - masterquiz-api
      - spacedrepetition-api
      - expense-tracker-api
      - masterquiz

  flashcards-api:
    extends:
      file: ./FlashCards-API/docker-compose.yml
      service: express
    expose:
      - "8000"
    restart: always
  masterquiz-api:
    extends:
      file: ./masterquiz-backend/docker-compose.yml
      service: express
    expose:
      - "8000"
    restart: always
  spacedrepetition-api:
    extends:
      file: ./Spaced-Repetition-Backend/docker-compose.yml
      service: express
    expose:
      - "8000"
    restart: always
  expense-tracker-api:
    extends:
      file: ./expense-tracker-backend/docker-compose.yml
      service: express
    expose:
      - "8000"
    restart: always
  masterquiz:
    extends:
      file: ./MasterQuiz-Frontend/docker-compose.yml
      service: web
    expose:
      - "80"
    restart: always
