version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.20.0-alpine
    volumes:
      - ./tempHomepage:/etc/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flashcards-api
      - masterquiz-api

  flashcards-api:
    extends:
      file: ./FlashCards-API/docker-compose.yml
      service: express
    expose:
      - "8000"
  masterquiz-api:
    extends:
      file: ./masterquiz-backend/docker-compose.yml
      service: express
    expose:
      - "8000"
